# Generated by Django 2.2.5 on 2020-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
