# Generated by Django 2.2.5 on 2020-01-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_bind',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_type',
        ),
    ]
