# Generated by Django 2.2.5 on 2020-01-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200113_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ncm',
            field=models.BigIntegerField(blank=True, default=False, null=True),
        ),
    ]
