# Generated by Django 2.2.5 on 2020-01-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200113_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
