# Generated by Django 2.2.5 on 2020-01-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('tax_ref', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=None, to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('situation', models.IntegerField(blank=True, null=True)),
                ('aliquot', models.FloatField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=None, to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ipi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('ipi_framework', models.IntegerField(blank=True, null=True)),
                ('ipi_situation', models.IntegerField(blank=True, null=True)),
                ('ipi_aliquot', models.FloatField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=None, to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Icm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('icms_code_cfop', models.FloatField(blank=True, max_length=200, null=True)),
                ('icms_situation', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=None, to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cofin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('cofins_situation', models.IntegerField(blank=True, null=True)),
                ('cofins_aliquot', models.FloatField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=None, to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
