# Generated by Django 2.2.5 on 2019-09-13 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_type', to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('descripiton', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_team', to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('descripiton', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_sector', to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.BigIntegerField(default=False)),
                ('rg', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('complement', models.CharField(max_length=150)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('neighborhood', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('number', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('civil_sate', models.CharField(blank=True, max_length=40, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(upload_to='media/images')),
                ('photo', models.ImageField(upload_to='media/images')),
                ('about', models.CharField(max_length=150)),
                ('is_term_accepted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_profile', to='company.Company')),
                ('user', models.ForeignKey(on_delete=None, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'default_permissions': ('view', 'add', 'delete', 'change'),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=150)),
                ('discount', models.FloatField(max_length=200)),
                ('minimum_order', models.IntegerField()),
                ('value', models.FloatField(max_length=200)),
                ('amount_of_points', models.IntegerField()),
                ('value_of_points', models.FloatField(max_length=200)),
                ('start_point_range', models.IntegerField()),
                ('end_point_range', models.IntegerField()),
                ('term_payment', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_level', to='company.Company')),
                ('type', models.ForeignKey(on_delete=None, to='users.Type')),
                ('user', models.ForeignKey(on_delete=None, related_name='person_level', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.BigIntegerField(blank=True, null=True)),
                ('rg', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=150)),
                ('complement', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('civil_sate', models.CharField(blank=True, max_length=40, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('is_term_accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_individual', to='company.Company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=None, related_name='person_individual', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=150)),
                ('discount', models.FloatField(max_length=200)),
                ('minimum_order', models.IntegerField()),
                ('value', models.FloatField(max_length=200)),
                ('amount_of_points', models.IntegerField()),
                ('value_of_points', models.FloatField(max_length=200)),
                ('start_point_range', models.IntegerField()),
                ('end_point_range', models.IntegerField()),
                ('term_payment', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_goal', to='company.Company')),
                ('type', models.ForeignKey(on_delete=None, to='users.Type')),
                ('user', models.ForeignKey(on_delete=None, related_name='person_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_contact', to='company.Company')),
                ('user', models.ForeignKey(on_delete=None, related_name='person_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Busines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.BigIntegerField()),
                ('company_name', models.CharField(max_length=150)),
                ('social_name', models.CharField(blank=True, max_length=150, null=True)),
                ('fancy_name', models.CharField(blank=True, max_length=150, null=True)),
                ('state_registration', models.BigIntegerField(blank=True, null=True)),
                ('municipal_registration', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=150)),
                ('complement', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('neighborhood', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('is_term_accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_business', to='company.Company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=None, related_name='person_business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_business', models.BooleanField(default=False)),
                ('is_individual', models.BooleanField(default=False)),
                ('is_collaborator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_bind', to='company.Company')),
                ('sector', models.ForeignKey(on_delete=None, to='users.Sector')),
                ('team', models.ForeignKey(on_delete=None, to='users.Team')),
                ('type', models.ForeignKey(on_delete=None, to='users.Type')),
                ('user', models.ForeignKey(on_delete=None, related_name='person_bind', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
