# Generated by Django 2.2.5 on 2019-09-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='company',
        ),
        migrations.AddField(
            model_name='type',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
