# Generated by Django 2.2.5 on 2019-09-30 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_auto_20190920_0212'),
        ('users', '0002_auto_20190920_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='busines',
            name='user_bond',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='person_business_bond', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individual',
            name='user_bond',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='person_individual_bond', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.BigIntegerField(blank=True, null=True)),
                ('rg', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=150)),
                ('complement', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('civil_sate', models.CharField(blank=True, max_length=40, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('is_term_accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_collaborator', to='company.Company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=None, related_name='person_collaborator', to=settings.AUTH_USER_MODEL)),
                ('user_bond', models.ForeignKey(blank=True, null=True, on_delete=None, related_name='person_collaborator_bond', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
