# Generated by Django 2.2.5 on 2020-01-16 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_profile_user'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='profile',
            name='user_bind',
        ),
        migrations.AddField(
            model_name='bind',
            name='user_bind',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(on_delete=None, to='company.Company'),
        ),
    ]