# Generated by Django 2.2.5 on 2019-09-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190930_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='name',
        ),
        migrations.AddField(
            model_name='busines',
            name='code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busines',
            name='registration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='registration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='registration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
