# Generated by Django 2.2.5 on 2020-01-17 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200116_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bind',
            name='user_bind',
        ),
        migrations.AlterField(
            model_name='bind',
            name='company',
            field=models.ForeignKey(on_delete=None, related_name='comapny_bind', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='bind',
            name='user',
            field=models.ForeignKey(on_delete=None, related_name='user_bind', to=settings.AUTH_USER_MODEL),
        ),
    ]
