# Generated by Django 2.2.5 on 2019-10-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190930_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='busines',
            name='about',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busines',
            name='photo',
            field=models.ImageField(default='', upload_to='photo/perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborator',
            name='about',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborator',
            name='photo',
            field=models.ImageField(default='', upload_to='photo/perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='about',
            field=models.CharField(default='img', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='photo',
            field=models.ImageField(default='my life', upload_to='photo/perfil'),
            preserve_default=False,
        ),
    ]
