# Generated by Django 2.2.5 on 2020-01-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200117_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bind',
            name='sector',
        ),
    ]
