# Generated by Django 2.2.5 on 2020-01-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_bind_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='bind',
            name='sector',
            field=models.ForeignKey(default='', on_delete=None, to='users.Sector'),
            preserve_default=False,
        ),
    ]
