# Generated by Django 2.2.5 on 2020-01-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_bind_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bind',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='users.Sector'),
        ),
    ]
