# Generated by Django 2.2.5 on 2019-10-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191015_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
