# Generated by Django 2.2.5 on 2019-10-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_collaborator_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busines',
            name='about',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='busines',
            name='anexo',
            field=models.ImageField(blank=True, null=True, upload_to='anexo/doc/business'),
        ),
        migrations.AlterField(
            model_name='busines',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='busines',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/perfil'),
        ),
    ]
