# Generated by Django 2.2.5 on 2020-01-17 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20200117_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='user_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
