# Generated by Django 2.2.5 on 2020-01-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_user_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_link',
        ),
    ]
