# Generated by Django 2.2.5 on 2019-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191017_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='about',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='anexo',
            field=models.ImageField(blank=True, null=True, upload_to='anexo/doc/collaborator'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='genre',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/perfil'),
        ),
    ]
