# Generated by Django 2.2.5 on 2019-10-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191017_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='enterprise_collaborator', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='date_register',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
