# Generated by Django 2.2.5 on 2020-01-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_bind_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cell',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
