# Generated by Django 2.2.5 on 2019-10-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191017_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='genre',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
