# Generated by Django 2.2.5 on 2019-10-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191017_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='anexo',
            field=models.ImageField(blank=True, default='/anexo', null=True, upload_to='anexo/doc/collaborator'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='photo',
            field=models.ImageField(blank=True, default='/anexo', null=True, upload_to='photo/perfil'),
        ),
    ]
