# Generated by Django 2.2.5 on 2019-10-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191017_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busines',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexo/doc/business'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='anexo',
            field=models.FileField(blank=True, default='/anexo', null=True, upload_to='anexo/doc/collaborator'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='anexo',
            field=models.FileField(upload_to='anexo/doc/individual'),
        ),
    ]
