# Generated by Django 2.2.5 on 2019-10-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191017_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='birthday',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
