# Generated by Django 2.2.5 on 2019-10-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191017_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
