# Generated by Django 2.2.5 on 2019-10-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191026_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
