# Generated by Django 2.2.5 on 2019-10-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191026_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='name_complete',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
