# Generated by Django 2.2.5 on 2019-10-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191028_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cell',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
