# Generated by Django 2.2.5 on 2019-10-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191029_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='kind_of_person',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='type_account',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
