# Generated by Django 2.2.5 on 2019-11-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20191029_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bind',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='users.Team'),
        ),
        migrations.AlterField(
            model_name='bind',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='users.Type'),
        ),
    ]
