# Generated by Django 2.2.5 on 2020-01-14 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_auto_20191101_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rg',
            field=models.IntegerField(blank=True, null=True),
        )


    ]
