# Generated by Django 2.2.5 on 2020-01-14 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_auto_20200114_1857'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='profile',
            name='bind',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='bind_user', to='users.Bind'),
        )
    ]
