# Generated by Django 2.2.5 on 2020-01-14 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_auto_20200114_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='company',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='user_bond',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='company',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='user',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='user_bond',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='bind',
            name='is_business',
        ),
        migrations.RemoveField(
            model_name='bind',
            name='is_collaborator',
        ),
        migrations.RemoveField(
            model_name='bind',
            name='is_individual',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='banner',
        ),
        migrations.AddField(
            model_name='profile',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexo/doc/individual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='matriculation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommendation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_bind',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='person_individual_bond', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(on_delete=None, related_name='enterprise_individual', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='complement',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_term_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='person_individual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Busines',
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
    ]
