# Generated by Django 2.2.5 on 2020-01-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_catalog_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=150)),
                ('initials', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
