# Generated by Django 2.2.5 on 2020-01-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.BigIntegerField()),
                ('name_company', models.CharField(max_length=150)),
                ('social_name', models.CharField(max_length=150)),
                ('fancy_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('complement', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('color_primary', models.CharField(max_length=150)),
                ('color_secudary', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=250)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_term_accepted', models.BooleanField(default=False)),
                ('logo', models.ImageField(upload_to='images/company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('discount', models.FloatField(max_length=200)),
                ('number_plan', models.IntegerField()),
                ('token', models.CharField(max_length=200)),
                ('amount_of_points', models.IntegerField()),
                ('value_of_points', models.FloatField(max_length=200)),
                ('resale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('term_payment', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simples_key', models.CharField(blank=True, default='Simples key', max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, default='Secret key', max_length=255, null=True)),
                ('company', models.OneToOneField(on_delete=None, related_name='key_company', to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=None, related_name='contact_company', to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.ForeignKey(on_delete=None, related_name='plan_company', to='company.Plan'),
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.BigIntegerField(blank=True, null=True)),
                ('initial_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('minimum_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('catalog', models.ForeignKey(on_delete=None, to='common.Catalog')),
                ('company', models.ForeignKey(on_delete=None, to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
