# Generated by Django 2.2.5 on 2019-09-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.BigIntegerField()),
                ('name_company', models.CharField(max_length=150)),
                ('social_name', models.CharField(max_length=150)),
                ('fancy_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('complement', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_term_accepted', models.BooleanField(default=False)),
                ('logo', models.ImageField(upload_to='images/company')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=None, related_name='contact_company', to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
