# Generated by Django 2.2.5 on 2019-09-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('discount', models.FloatField(max_length=200)),
                ('number_plan', models.IntegerField()),
                ('token', models.CharField(max_length=200)),
                ('amount_of_points', models.IntegerField()),
                ('value_of_points', models.FloatField(max_length=200)),
                ('resale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('term_payment', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=None, related_name='plan_company', to='company.Plan'),
            preserve_default=False,
        ),
    ]
