# Generated by Django 2.2.5 on 2019-10-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190920_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simples_key', models.CharField(blank=True, default='3b7894bc77b1c7a060b994a748e362a56d42f7e5', max_length=125, null=True)),
                ('secret_key', models.CharField(blank=True, default='f13b23f73daf27ebe49b2079c7842cf35a425af3b9e22cebfa4d728b1507118187d6c8bd00a5d7329c3f16681903a4afeac3', max_length=125, null=True)),
                ('company', models.ForeignKey(on_delete=None, related_name='key_company', to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
