# Generated by Django 2.2.5 on 2019-10-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='ccab2fdb54bce0d0a1f54b17dc9417b4a6279f3292d624b66d725939f76e531619140147efbcbbd1c86aa18fb08e5d3e4312', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='fba16d3595b19f8e858c7e6bd15febca11620133', max_length=125, null=True),
        ),
    ]
