# Generated by Django 2.2.5 on 2019-10-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20191015_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='717002fa5dcc327fb5652d749e15d18fabe9a476d6b0abab70d971d1b8fa1f0588599df9fb3caf051e869ffe46328343782d', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='ebca419a201a41cdb134bf3699426c44be88dc9d', max_length=125, null=True),
        ),
    ]
