# Generated by Django 2.2.5 on 2019-10-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20191015_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='643e2f6874bc1b931793eefd5f7b0bcfedeaf07302f21694d4533a2dc1f0f557d425cdd647405b2aedc16c6712fe20c8f5a6', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='a3c7f908e079771165c31dc64e62d452b85632fe', max_length=125, null=True),
        ),
    ]
