# Generated by Django 2.2.5 on 2019-10-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20191015_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='3cbd4b8f23df2243c8b93aac87a7c2318af4c1a53cb3c985e9e31cf8da1effb97af895cb3e22dbc50900ee82d411d1e511ad', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='38baa087dd31b2500809d4fb2bb096003bb53199', max_length=125, null=True),
        ),
    ]
