# Generated by Django 2.2.5 on 2019-10-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20191015_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='50e446e5fb56daf9b189fd0105e7b06b7c2b87f4d19319515ea9f279f9addd94d573fe4d98f11171196e90ef739ede0833ca', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='fde8f4efb3c2d5740f35c40f3bebb499bde85810', max_length=125, null=True),
        ),
    ]
