# Generated by Django 2.2.5 on 2019-10-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20191015_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='d68e6e9369b7d4214de8fe91bddb2f38d2bf6bced4ec7afc2b46bed5424e118d1fdbf65ed8100e0a129127510c2cbab81f6f', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='431066c3e38cc7a11c53584a3b28ab060c9ca8b8', max_length=125, null=True),
        ),
    ]
