# Generated by Django 2.2.5 on 2019-10-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20191015_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='d3503caf5dbebf4e135573e401f23d3a9e1f7c0039247a0a1d1bb2736b5626ffbc9ad861da56b61741fd153b587b9a5d38c6', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='e0839971ddf94285730f6f77c150b3e5620b9b45', max_length=125, null=True),
        ),
    ]
