# Generated by Django 2.2.5 on 2019-10-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20191015_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='afd21bca87b7c0b5bfa21a45d0b995faf7e2ef3cea06914f00138350048dc86a09fce8deccaa7e8db86b43575d8173db8dfa', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='8ce51c6943eefdc3ca7c708babf4962ba93fc932', max_length=125, null=True),
        ),
    ]
