# Generated by Django 2.2.5 on 2019-10-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20191017_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='84b6814f8a8ff543d5aacb3a23e32519a44f72c5a18d69eaadc6ac1ca82cae3e4ea31da940bfae6327938af0a4f0ab8c922d', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='6e8c55ab2d3d5381eecec8699d0246945225bacb', max_length=125, null=True),
        ),
    ]
