# Generated by Django 2.2.5 on 2019-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20191017_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='b0128f65b1959eb7bc232920227919c17b04b7552989753f1e8985e4d19778f0d770b0ddf921304050a15c37d9d7009dbaa7', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='7cf316bb60f62d0f08ac10ca6fed9ec1799e8b9f', max_length=125, null=True),
        ),
    ]
