# Generated by Django 2.2.5 on 2019-10-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20191017_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='17e9881748a3c7aaf3df9508715c7f275ad19e8600103eec4669ffdbd0e005dc53f4a9b7cb988d3a976a766705b117b63577', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='3582c66c0a062081bcffac20871e41ffe10b2be2', max_length=125, null=True),
        ),
    ]
