# Generated by Django 2.2.5 on 2019-10-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20191017_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='33b5c0de25e3dbadbc59084991cd7841a13b0aacaf1393e76d8b465ad35c33c0fde7e323bb112320171a7a1f0a636c700da0', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='7fa7dee6d58deab819b302326b46c081e64eafd0', max_length=125, null=True),
        ),
    ]
