# Generated by Django 2.2.5 on 2019-10-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20191017_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='956955b2dcd3bc0fc335135f4dab9277eae6107624300a9d3a85b46c39afe915b6e5c461298fa10752d7cc52ae7edcbaa24c', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='d2e97295dfd52bf920ba65d4679d31aef5aa4f27', max_length=125, null=True),
        ),
    ]
