# Generated by Django 2.2.5 on 2019-10-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20191017_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='d9e87ae9e819651808ca969690296d8ceab2f9f126d764789a17378a36438260c7cd7641acc70ba6083c0b790fd537454b8b', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='774173662a7a4e7b4ed68e5d5e9895be3f8a4e8e', max_length=125, null=True),
        ),
    ]
