# Generated by Django 2.2.5 on 2019-10-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20191017_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='b29f8ce36770ded2d1e3f23d60c14d9d6046fc591489393fc9648783e9cd7f60d0dee50f32a638cba18e5a1bcbeae8479627', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='5ae5790ef582cfbb392cb72d8b6f48fc95603fec', max_length=125, null=True),
        ),
    ]
