# Generated by Django 2.2.5 on 2019-10-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20191017_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='b9bf42180b0a466d3a9560278da1f128cf418fb7b0eb565530f9ebf0e800920d9d907d35aec4b38c4c58941b907fb76623ac', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='0baa093e169d6e6668b6b93d34f734545b32da67', max_length=125, null=True),
        ),
    ]
