# Generated by Django 2.2.5 on 2019-10-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20191017_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='619a7279db14a60dfe51db9edb34f75dae1a2b5092b29480fed31b22264ee60c7e267d65e3e23013aa3cff94783a740288b6', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='260e582024b254522eb69efb1628f2afe15d6eed', max_length=125, null=True),
        ),
    ]
