# Generated by Django 2.2.5 on 2019-10-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_auto_20191017_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='9cb2d3c6a58f8e7ba0ff5836b6a470484d2cc27c23a82b12f763b667dcf0654c60a67d4396a4306af35e3ba9003b19af5c18', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='1aa6001e9b53feccd903108682154eb67fd481fc', max_length=125, null=True),
        ),
    ]
