# Generated by Django 2.2.5 on 2019-10-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20191017_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='47e4ea7ea71995e20d490e0da0b2aa1bba6e605aaec8a5b5bed6a0790271be100f940490ce44730e66b0fc21f12e1a64db44', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='0a373a425030e1a698386031eb0ed301a198d62c', max_length=125, null=True),
        ),
    ]
