# Generated by Django 2.2.5 on 2019-10-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20191017_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default='434b4ec6b28a7c3877d312d6bf21e421b49dd557ca91334df2f9bd162668d6335d61bb95255a5af52af6bd17307ea92f2902', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default='3ca072ea0cefc7a860e79684f4507a8de64046a2', max_length=125, null=True),
        ),
    ]
