# Generated by Django 2.2.5 on 2019-10-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20191026_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiZmEyZTI3ZDliODM2NGZjNzU4YzU4YjEyNzIwZTRhYzllNWM2ZjM2MzVkNDhhYzAyNzY3MGIyYTdmZDlhY2EwMzEwZjBjZjY3NTM4OGZiMTQ2MDczZDUxZWE3MDJlNjU0ZTFjNSJ9.gaRy3zEAQNsnpXh29gAERRnofYMkUsnACfC-WS_03do', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiMDkxZWQ1MjVjY2NhN2YyZmFhNzliMTdkMTQ5MzFlMTlhODAwOTlhNSJ9.dtyPkPpkvnlntyQj_2g-T-l6pbv6h9Y1dcKZoUAHmm4', max_length=255, null=True),
        ),
    ]
