# Generated by Django 2.2.5 on 2019-10-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_auto_20191026_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiNThiYjEyMjI5ZmYxNGJlNjcwMjljNjFhZWVhMTRkZWI4YWY1MzJmNmNhOThjNDljMzBlYzQyZDg5YTM0NWJiMTJkNTVlYTU3ZTViNWIzYjE2Yjg3MWExOGM5YmMxMTg4MThiZiJ9.k2hV4hZqFseLrIlTAdzOEgJMN8FtjzpP7aezPm14QSg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiNDBiMzQxZTY4ZjRlNWNkZWVjNGIyNDA1ZGExYThkYjZkOTMzYTI3NSJ9.oiTxwQjW7yQgm0EBVd63IJeogl1hKtP1t3Rqf7H8oU8', max_length=255, null=True),
        ),
    ]
