# Generated by Django 2.2.5 on 2019-10-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20191026_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiNTgyNmZiNGFiMTc4MjYwMjgzNWE0MGFlNDBhNzc0MGM2OWY3ODRiMzhmYTZiYzA4ODk3ZjdlMzMxMjIxOTYzNmYzNjlmMzg2MzA2MjAyYTI0ODQ4OTA5ODc2ZDE1OWI4MGU3YiJ9.sl4-1o114vni78PA5UL_69JJINAExUPJt8zltIgeFeo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiNWQ3OTMzY2E1NjBjNjc5MWJkOGE4MDY5NjA0NGI3OWU0NTQ1M2Y3OSJ9.FOGTvfjRVusWFIckTdrQNk9dLTjqfoC7lEtOtNuXTuI', max_length=255, null=True),
        ),
    ]
