# Generated by Django 2.2.5 on 2019-10-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_auto_20191029_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiNGE1YjlmY2U4YWVmMTAyYTVlZjIyNzUwZGJkMTFmMGVkOWYxZTJmNDY0ZjA0NDQ2MjI5ODg4ZDNjZDEyOTY4Mzk1ODY0Y2ZlNjc0ZTkyZmIwYTdjNzEwOTEwNDkxZjZiZGFhNCJ9.LvpmOLyJZKoJeZYP2QQ7JbNGGqhqKiIsqPq-HBFCQdI', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiN2YzM2I5NzAwODZjNmNhOWY0ZjNkMGRjN2RiMzM4NGRkOGIxMTc0ZSJ9.EUL4HglSWP0LqOoHR-EHjFksZLMOe5paQv7NJLXpSKM', max_length=255, null=True),
        ),
    ]
