# Generated by Django 2.2.5 on 2019-11-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_auto_20191030_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiM2U3ZTI3YTljYjdiYTVhMWI0NzFiMjlhYmI0NjU1MTU2ZDgwZjcyMGY5ZGY3MmQwZjk2NTYzMGFhZjNiOWY2NGNiMDU5N2FhZDAzZjY4ZmYzZmRkNWY4NWJmMDM2NmE4YTg5OCJ9.8JQeGBv_6vXRTpATk8wYTjjDu0PNQTCEyzjsjSpKU3s', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(blank=True, default=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55IjoiZWJhM2RjMmM1NDFjNzI1YWRkNDI1OGVhZDFlMTI4NmVhZDU3Njk5OSJ9.RCSoT9AHhzhMRVvwXBl3VGYPeouE040mg91kV6IInpI', max_length=255, null=True),
        ),
    ]
