# Generated by Django 2.2.5 on 2019-11-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_auto_20191101_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(default='KEY SECRET', max_length=255),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(default='KEY SIMPLES', max_length=255),
        ),
    ]
