# Generated by Django 2.2.5 on 2019-11-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_auto_20191101_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='secret_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='key',
            name='simples_key',
            field=models.CharField(max_length=255),
        ),
    ]
