# Generated by Django 2.2.5 on 2019-11-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_auto_20191105_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='key',
            name='company',
            field=models.OneToOneField(on_delete=None, related_name='key_company', to='company.Company'),
        ),
    ]
