# Generated by Django 2.2.5 on 2019-12-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_auto_20191106_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color_primary',
            field=models.CharField(default='#0000', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='color_secudary',
            field=models.CharField(default='#fffff', max_length=150),
            preserve_default=False,
        ),
    ]
