# Generated by Django 2.2.5 on 2020-01-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('company', '0038_auto_20191218_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.BigIntegerField(blank=True, null=True)),
                ('initial_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('minimum_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('catalog', models.ForeignKey(on_delete=None, to='common.Catalog')),
                ('company', models.ForeignKey(on_delete=None, to='company.Company')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
