# Generated by Django 2.2.5 on 2020-01-17 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('product', '0001_initial'),
        ('company', '0001_initial'),
        ('common', '0001_initial'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('initials', models.CharField(blank=True, max_length=1, null=True)),
                ('code', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=None, related_name='enterprise_request_status', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('billing_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_customer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('freight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('request_number', models.BigIntegerField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.ForeignKey(on_delete=None, to='campaign.Campaign')),
                ('catalog', models.ForeignKey(on_delete=None, to='company.Catalog')),
                ('company', models.ForeignKey(on_delete=None, to='company.Company')),
                ('lot', models.ForeignKey(on_delete=None, to='lote.Lote')),
                ('payment_methods', models.ForeignKey(blank=True, null=True, on_delete=None, to='common.Payment_methods')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('status', models.ForeignKey(default=1, on_delete=None, to='request.Status')),
                ('user_bind_typeit', models.ForeignKey(blank=True, null=True, on_delete=None, related_name='user_typeit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_checked', models.BooleanField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=None, to='product.Product')),
                ('request', models.ForeignKey(on_delete=None, to='request.Request')),
            ],
        ),
    ]
