# Generated by Django 2.2.5 on 2020-01-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191101_1655'),
        ('company', '0039_catalog'),
        ('common', '0003_payment_methods'),
        ('lote', '0002_auto_20200113_1919'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date_register',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='business',
        ),
        migrations.RemoveField(
            model_name='request',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='request',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='request',
            name='total',
        ),
        migrations.AddField(
            model_name='request',
            name='amount_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='catalog',
            field=models.ForeignKey(default='', on_delete=None, to='company.Catalog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='commission_customer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='is_user_bind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='lot',
            field=models.ForeignKey(default='', on_delete=None, to='lote.Lote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_methods',
            field=models.ForeignKey(default='', on_delete=None, to='common.Payment_methods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='request_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_bind',
            field=models.ForeignKey(blank=True, default='', on_delete=None, to='users.Bind'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
