# Generated by Django 2.2.5 on 2020-01-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=None, to='campaign.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itens',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
