# Generated by Django 2.2.5 on 2020-01-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20200115_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=1, on_delete=None, to='request.Status'),
        ),
    ]
