# Generated by Django 2.2.5 on 2020-01-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20200114_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user_bind',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='users.Bind'),
        ),
    ]
