# Generated by Django 2.2.5 on 2020-01-16 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200116_1959'),
        ('request', '0003_auto_20200115_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_user_bind',
        ),
        migrations.AddField(
            model_name='request',
            name='bind',
            field=models.ForeignKey(default='', on_delete=None, to='users.Bind'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='user_bind',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
