# Generated by Django 2.2.5 on 2020-01-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20200114_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_methods',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='common.Payment_methods'),
        ),
    ]
