# Generated by Django 2.2.5 on 2020-01-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20200114_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
