# Generated by Django 2.2.5 on 2020-01-16 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0004_auto_20200116_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user_bind',
        ),
        migrations.AddField(
            model_name='request',
            name='user_bind_typeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='user_typeit', to=settings.AUTH_USER_MODEL),
        ),
    ]
