# Generated by Django 2.2.5 on 2020-01-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200117_0048'),
        ('request', '0005_auto_20200116_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='bind',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='profile',
            field=models.ForeignKey(default='', on_delete=None, to='users.Profile'),
            preserve_default=False,
        ),
    ]
