# Generated by Django 2.2.5 on 2020-01-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20200117_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='users.Profile'),
        ),
    ]
