# Generated by Django 2.2.5 on 2020-01-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_form',
            name='company',
        ),
        migrations.AlterField(
            model_name='sale',
            name='flags_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='common.Flags_card'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='common.Payment_methods'),
        ),
        migrations.DeleteModel(
            name='Flags_card',
        ),
        migrations.DeleteModel(
            name='Payment_form',
        ),
    ]
